baseURL = "https://www.creaturelove7.com/"  # 改成你的域名，如 "https://renrenzhang.com/"
languageCode = "en"
title = "Renren Zhang"
theme = "PaperMod"

# Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tech"
  url = "/tech/"
  weight = 2

[[menu.main]]
  name = "Career"
  url = "/career/"
  weight = 3

[[menu.main]]
  name = "AI"
  url = "/ai/"
  weight = 4

[[menu.main]]
  name = "Books"
  url = "/books/"
  weight = 5

[[menu.main]]
  name = "Money"
  url = "/money/"
  weight = 6

[params]
  description = "Tech | Career | AI | Books | Money"
  mainSections = ["ai", "books", "tech", "money", "career"]
  author = "Renren Zhang"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"

  [params.assets]
    favicon = "favicon.svg"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    style = "monokai"