baseURL = "https://www.creaturelove7.com/"  # 改成你的域名，如 "https://renrenzhang.com/"
languageCode = "en"
title = "Renren Zhang"
theme = "PaperMod"

[pagination]
  pagerSize = 10

enableEmoji = true

[params]
  description = "Renren Zhang's Personal Blog"
  author = "Renren Zhang"
  
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  
  defaultTheme = "auto"

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    style = "monokai"
